2018-12-28 00:08:13,321 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/auth/routes.py", line 60, in reset_password_request
    send_password_reset_email(user)
  File "/Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/auth/email.py", line 13, in send_password_reset_email
    user=user, token=token
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/auth/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/peregrinedunn/.pyenv/versions/3.5.2/envs/hipflask/lib/python3.5/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2018-12-28 00:11:44,039 INFO: Microblog startup [in /Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/__init__.py:71]
2018-12-28 00:21:59,128 INFO: Microblog startup [in /Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/__init__.py:71]
2018-12-28 00:23:35,987 INFO: Microblog startup [in /Users/peregrinedunn/Documents/projects/perrydunn/flask-app/app/__init__.py:71]
